name: CI

on:
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 5 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check
  test:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Specs
        run: crystal spec --order random --error-on-warnings
