name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install --production
      - name: Build
        run: crystal doc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@2.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
